CREATE TABLE IF NOT EXISTS modules (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  prerequisites TEXT,
  icon VARCHAR(64) DEFAULT 'book',
  image_url VARCHAR(500),
  background_color CHAR(7) DEFAULT '#EAF2FF',
  order_index INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS lessons (
  id INT AUTO_INCREMENT PRIMARY KEY,
  module_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  content LONGTEXT,
  read_time INT DEFAULT 5,
  lesson_order INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (module_id) REFERENCES modules(id) ON DELETE CASCADE,
  INDEX idx_module_order (module_id, lesson_order)
);

CREATE TABLE IF NOT EXISTS app_content (
  id INT PRIMARY KEY,
  welcome_title VARCHAR(255) NOT NULL,
  welcome_description TEXT NOT NULL,
  motivation_text TEXT NOT NULL,
  motivation_quote TEXT NOT NULL,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
